graalvm: override method to avoid native image error
it seems without overriding it the native image generation was pruning the `buildMcpServerSpec` method

```
% build/native/nativeCompile/micronaut-guide
17:28:13.224 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.modelcontextprotocol.server.McpSyncServer]

Message: Required method buildMcpServerSpec(Object,McpServerInfoConfiguration,ToolsConfiguration,PromptsConfiguration,ResourcesConfiguration,Builder,Provider,ToolRegistry,PromptRegistry,ResourceRegistry,List,List,List,List,List) not found for class: io.micronaut.mcp.server.stdio.sync.McpServerSyncFactory. Most likely cause of this error is the method declaration is not annotated with @Executable. Alternatively check that there is not an unsupported or older version of a dependency present on the classpath. Check your classpath, and ensure the incompatible classes are not present and/or recompile classes as necessary.
Path Taken:
@j.i.Singleton i.m.s.McpSyncServer i.m.m.s.s.s.McpServerSyncFactory.createMcpSyncServer#createMcpSyncServer(SyncSpecification<SyncSpecification<SyncSpecification<Object>>> syncSpecification)
\---> @j.i.Singleton i.m.s.McpSyncServer i.m.m.s.s.s.McpServerSyncFactory.createMcpSyncServer#createMcpSyncServer([SyncSpecification<SyncSpecification<SyncSpecification<Object>>> syncSpecification])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.modelcontextprotocol.server.McpSyncServer]

Message: Required method buildMcpServerSpec(Object,McpServerInfoConfiguration,ToolsConfiguration,PromptsConfiguration,ResourcesConfiguration,Builder,Provider,ToolRegistry,PromptRegistry,ResourceRegistry,List,List,List,List,List) not found for class: io.micronaut.mcp.server.stdio.sync.McpServerSyncFactory. Most likely cause of this error is the method declaration is not annotated with @Executable. Alternatively check that there is not an unsupported or older version of a dependency present on the classpath. Check your classpath, and ensure the incompatible classes are not present and/or recompile classes as necessary.
Path Taken:
@j.i.Singleton i.m.s.McpSyncServer i.m.m.s.s.s.McpServerSyncFactory.createMcpSyncServer#createMcpSyncServer(SyncSpecification<SyncSpecification<SyncSpecification<Object>>> syncSpecification)
\---> @j.i.Singleton i.m.s.McpSyncServer i.m.m.s.s.s.McpServerSyncFactory.createMcpSyncServer#createMcpSyncServer([SyncSpecification<SyncSpecification<SyncSpecification<Object>>> syncSpecification])
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2352)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3150)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:3027)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2762)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1781)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:210)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2130)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1360)
	at io.micronaut.mcp.server.stdio.sync.$McpServerSyncFactory$CreateMcpSyncServer1$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2337)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3150)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:3000)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2762)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1781)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:855)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:847)
	at io.micronaut.mcp.server.McpServerBootstrap.onStartupEvent(McpServerBootstrap.java:48)
	at io.micronaut.mcp.server.$McpServerBootstrap$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3987)
	at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:91)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:143)
	at io.micronaut.mcp.server.McpServerBootstrap$ApplicationEventListener$onStartupEvent1$Intercepted.onApplicationEvent(Unknown Source)
	at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1867)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:368)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:225)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
	at example.micronaut.Application.main(Application.java:10)
	at java.base@21.0.7/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.NoSuchMethodError: Required method buildMcpServerSpec(Object,McpServerInfoConfiguration,ToolsConfiguration,PromptsConfiguration,ResourcesConfiguration,Builder,Provider,ToolRegistry,PromptRegistry,ResourceRegistry,List,List,List,List,List) not found for class: io.micronaut.mcp.server.stdio.sync.McpServerSyncFactory. Most likely cause of this error is the method declaration is not annotated with @Executable. Alternatively check that there is not an unsupported or older version of a dependency present on the classpath. Check your classpath, and ensure the incompatible classes are not present and/or recompile classes as necessary.
	at io.micronaut.core.reflect.ReflectionUtils.newNoSuchMethodError(ReflectionUtils.java:439)
	at io.micronaut.core.reflect.ReflectionUtils.lambda$getRequiredMethod$0(ReflectionUtils.java:263)
	at java.base@21.0.7/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.core.reflect.ReflectionUtils.getRequiredMethod(ReflectionUtils.java:263)
	at io.micronaut.mcp.server.stdio.sync.$McpServerSyncFactory$BuildMcpServerSpec0$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2337)
	... 31 common frames omitted
``